language: java

cache:
  directories:
    - '$HOME/.m2/repository'

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn -DskipTests=true clean install

branches:
  only:
    - master