server:
  port: 9010
  servlet:
    context-path: /explore-api/

# mysql
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.9.80:3306/github_explore?characterEncoding=utf-8
      username: root
      password: root.2019
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 10
      min-idle: 3
      initial-size: 5
  aop:
    proxy-target-class: true
mybatis:
  mapper-locations: classpath:explore-dao-mapper/*.xml
  type-aliases-package: net.abc.explore.entity

# mybatis sql 打印
logging:
  level:
    net:
      abc:
        explore: info

# swagger
swagger:
  enabled: false
  title: explore-rest-api
  description: api list
  version: 1.0-SNAPSHOT
  contact:
    name: zhangwei
    email: pknfe@outlook.com
  base-package: net.abc.explore.rest.api.controller